[package]
name = "tss"
version = "0.0.1-dev"
authors = ["Leung Yau Ming <leungyauming2005@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
clap = "2.33.3"
