name: tss

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release --verbose

    - uses: actions/upload-artifact@v2
      with:
        name: tss_${{ matrix.platform }}
        path: ./target/release/tss[.exe]
